// ── JSON → SQL INSERT converter ──────────────────────────────────────

export type SqlDialect = 'mssql' | 'mysql' | 'postgres'

function escapeVal(val: unknown, dialect: SqlDialect): string {
  if (val === null || val === undefined) return 'NULL'
  if (typeof val === 'boolean') {
    if (dialect === 'mssql') return val ? '1' : '0'
    return val ? 'TRUE' : 'FALSE'
  }
  if (typeof val === 'number') return String(val)
  if (typeof val === 'object') return `'${JSON.stringify(val).replace(/'/g, "''")}'`
  const s = String(val).replace(/'/g, "''")
  return `'${s}'`
}

function quoteIdentifier(name: string, dialect: SqlDialect): string {
  if (dialect === 'mysql') return `\`${name}\``
  if (dialect === 'postgres') return `"${name}"`
  return `[${name}]`
}

export function convertJsonToSql(
  json: string,
  tableName: string,
  dialect: SqlDialect,
  batchSize = 1
): string {
  const parsed = JSON.parse(json)
  const rows: Record<string, unknown>[] = Array.isArray(parsed) ? parsed : [parsed]

  if (!rows.length) return '-- No rows to insert.'

  const qt = quoteIdentifier(tableName, dialect)
  const allKeys = Array.from(new Set(rows.flatMap(r => Object.keys(r))))
  const cols = allKeys.map(k => quoteIdentifier(k, dialect)).join(', ')

  const lines: string[] = [
    `-- Generated by FenaQuery · Dialect: ${dialect.toUpperCase()}`,
    `-- Table: ${tableName} · Rows: ${rows.length}`,
    '',
  ]

  if (batchSize === 1 || dialect !== 'postgres') {
    // Individual INSERTs (MSSQL / MySQL default) or single-row
    for (const row of rows) {
      const vals = allKeys.map(k => escapeVal(row[k] ?? null, dialect)).join(', ')
      lines.push(`INSERT INTO ${qt} (${cols}) VALUES (${vals});`)
    }
  } else {
    // Batch INSERT (Postgres)
    for (let i = 0; i < rows.length; i += batchSize) {
      const batch = rows.slice(i, i + batchSize)
      const valueRows = batch
        .map(row => `  (${allKeys.map(k => escapeVal(row[k] ?? null, dialect)).join(', ')})`)
        .join(',\n')
      lines.push(`INSERT INTO ${qt} (${cols})\nVALUES\n${valueRows};`)
    }
  }

  return lines.join('\n')
}
